### PR TITLE
[MIRROR] Replace radio frequency magic numbers with defines

### PR DESCRIPTION
**Pull request by RepoCat**
Original PR: https://github.com/tgstation/tgstation/pull/33236
--------------------
:cl:
fix: Radio frequency 148.9 is once again serviced by the telecomms system.
/:cl:

Telecomms code is infamously bad, and as a prelude to fixing that, this PR begins to clean up radio code in general by switching radio-related magic numbers and globconsts to defines.

The telecomms machines which include general frequencies no longer exclude the last one, 148.9, which is tunable by radios but was previously not subspace-capable.

One particular piece of apparently unused equipment, the simple vent controller, is changed to a different frequency. It doesn't seem like anything receives on the old frequency, so I saved on adding a define solely for the benefit of dead code.

### CODE REVIEW

**Review by Partheo — COMMENTED** [review]
If we want NTSL, we better port that first before merging this. Y/N?

**Comment by praisenarsie** [comment]
ntsl is 10 year old code and stupid, just merge this.

**Comment by Kevak** [comment]
Frankly I don't think NTSL is a good idea Par. It's 'fun' but it's too easy to crash the server with. Maybe with major sanitizing checks.

**Review by Kevak — APPROVED** [review]
Gonna go ahead and approve this but hold off merge till Par comments.

**Comment by Partheo** [comment]
I still think NTSL is a good idea, but I'd rather merge this now and figure it out later.

As for the server crash thing, I think we have different ideas of what it is- I'd merge 2014-2014 NTSL in, which is much safer and doesn't have the bullshit that Paradise's NTSL has.

**Pull request merged**
