### PR TITLE
Adds transceivers

### PR DESCRIPTION
**Pull request by Amelia0010**
on the portlist. I'll add em to the map tomorrow.

:cl:
add: Security now have transceivers, meaning they can communicate in the event of a blackout.
/:cl:

### CODE REVIEW

**Review by Partheo — APPROVED** [review]

**Comment by Partheo** [comment]
Can you add these to:
1. The captain's locker
2. The HoS' locker
3. The warden's locker
4. Security closets

5. HoS box
6. Detective box
7. Sec officer box

Check this for details.
https://github.com/yogstation13/yogstation/search?utf8=%E2%9C%93&q=%2Fradio%2Fsecurity&type=

**Comment by Amelia0010** [comment]
I completely forgot about this. I'll do it when I get home from work later

**Comment by Kevak** [comment]
Making Travis recheck

**Comment by Kevak** [comment]
Actually fixed the conflict for reals.

**Pull request merged**
