### PR TITLE
New Lobby Screen

### PR DESCRIPTION
**Pull request by Amelia0010**
hi rory

### CODE REVIEW

**Review by ActualRory — APPROVED** [review]
What the shitsnacks?

**Comment by ActualRory** [comment]
https://pasteboard.co/GXrH4Si.png

**Comment by ActualRory** [comment]
Yep, this is mine. You magical mastermind.

**Comment by ActualRory** [comment]
Best double check with Parth if this works with our strange current system.

**Review by Partheo — CHANGES_REQUESTED** [review]
Put this in /haven/config, not /config.

**Pull request closed without merging**
