### PR TITLE
Configstuff tweaks.

### PR DESCRIPTION
**Pull request by Kevak**
[Changelogs]: Adjusts configs.

:cl: Neri
tweak: Minor config tweaks.
balance: Adjusts nutrientloss. May tweak further. You should not need to eat 5 pizzas in one shift.
fix: Enables mutanthumans.
spellcheck: Fixes a misspell in a config comment.
config: Adjusts weighting on things, enables some settings, enables more roundstart races. Stops NT from hiring teenagers, and so on. Easier to just skim the PR.
server: Adjusts configs, enables a couple things. (If starlight being enabled starts causing serious lag. Disable that shit.)
/:cl:

Couple things were disabled that shouldn't be, couple things needed to be altered. And so on. Open for adjustments as required.

### CODE REVIEW

**Comment by Kevak** [comment]
@Partheo and @ActualRory Give this a looksie.

**Review by Partheo — DISMISSED** [review]
Make your config changes to /haven/config, not /config.

**Comment by Kevak** [comment]
Done.

**Review by ActualRory — COMMENTED** [review]
Fine with all of this except shadowpeeps at roundstart, they hardly add much to the experience if they're living in maint. One we port slings they'll probs be a cluster fuck too.

**Comment by praisenarsie** [comment]
>roundstart shadow

its like you guys don't even play /tg/! oh right you play yog 😄

**Comment by Kevak** [comment]
To be totally honest. I just wanna see someone rp out the misery of being a shadowperson. I heavily suspect nobody will actually do that outside of one or two rounds.

It is on my list to overhaul em to be viable to play. Prolly with some form of protective suit ala plasmemes.

**Comment by Kevak** [comment]
Nixed roundstart shadow till I actually get around to overhauling em. Ideally we want this merged sooner rather than later to prevent Broken Gamemodes and similar from popping up.

**Comment by Kevak** [comment]
@Partheo This has been ready for like two days.

**Review by ActualRory — APPROVED** [review]
Approved via discussion.

**Pull request merged**
