### PR TITLE
[MIRROR] Limit bullet overlays on walls

### PR DESCRIPTION
**Pull request by RepoCat**
Original PR: https://github.com/tgstation/tgstation/pull/33364
--------------------
Badcode

### CODE REVIEW

**Comment by Kevak** [comment]
Mm. I'm iffy on merging this. I sorta prefer more holes rather than less holes. @Partheo thoughts?

**Comment by Partheo** [comment]
@Kevak If we're iffy on merging it, I say we merge it to avoid conflicts down the line. I'm fine with the change.

**Comment by Kevak** [comment]
It’s a nonmajor code change that is highly unlikely to result in conflicts. I think I’ll just turn up the bullet hole limit to something more immersive and then merge it.

**Review by Kevak — APPROVED** [review]
Did what I said I'd do. Code's good.

**Comment by Partheo** [comment]
Good compromise, and points for the reference 👍

**Pull request merged**
