### PR TITLE
[MIRROR] Datumizes saymodes

### PR DESCRIPTION
**Pull request by RepoCat**
Original PR: https://github.com/tgstation/tgstation/pull/33013
--------------------
Swarmer chat, blob chat, alien chat, ling chat, silicon chat, drone chat, golem chat, ALL DATUMIZED!

### CODE REVIEW

**Comment by Kevak** [comment]
Travis seems displeased. @Partheo I have no idea what Travis's displeasure is about. Mind walkin me through that?

**Comment by Partheo** [comment]
Whenever a TG mirror adds a new file, we'll have to update our .dme manually, or Travis will get an error. It's a good thing that it checks for us.

**Comment by Kevak** [comment]
Ja.

**Comment by Kevak** [comment]
Sidenote. This'll make something I was planning on adding later easier.

**Pull request merged**
