### PR TITLE
[MIRROR] adds handholding

### PR DESCRIPTION
**Pull request by RepoCat**
Original PR: https://github.com/tgstation/tgstation/pull/33831
--------------------
target arms while pulling
image
image

### CODE REVIEW

**Comment by Hatterhat** [comment]
>the screencap of my shitpost has drastically lowered in quality

smh

**Comment by Kevak** [comment]
Travis.

**Comment by Kevak** [comment]
Travis.

**Review by Kevak — APPROVED** [review]
Absolutely Degenerate.

**Pull request merged**
