### PR TITLE
[MIRROR] Fixes certain material containers

### PR DESCRIPTION
**Pull request by RepoCat**
Original PR: https://github.com/tgstation/tgstation/pull/33370
--------------------
Fixes #33321

I just realized every material container sets max_amount to 0 and still works anyway. UMMMMMMMM.....

### CODE REVIEW

**Review by Kevak — APPROVED** [review]
Fixed ze conflicts.

**Comment by Kevak** [comment]
Hum still a conflict.

**Comment by Kevak** [comment]
Uh.. Hum. @Partheo Not sure what else is causing the conflict.

**Comment by Partheo** [comment]
@Kevak Looks fine now, is the issue resolved?

**Comment by Kevak** [comment]
Travis still claims there’s a conflict on my end. Are ye seeing that?

**Comment by Kevak** [comment]
@Partheo there is a travis issue and I do not know what is causing it. Assistance requested.

**Pull request closed without merging**
